apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak-0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
        petindex: "0"
    spec:
      containers:
        - name: keycoak
          image: solsson/keycloak-ha-postgres:2.3.0.Final
          ports:
            - containerPort: 8080
            - containerPort: 45700
            - containerPort: 7600
            - containerPort: 57600
            - containerPort: 55200
            - containerPort: 45688
            - containerPort: 54200
            - containerPort: 23364
            - containerPort: 4712
            - containerPort: 4713
          env:
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
            - name: POSTGRES_ROOT_PASSWORD
              value: password
            # first start only, testing only
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: test
          args:
            - -b=0.0.0.0
            - -bmanagement=0.0.0.0
            - --server-config=standalone-ha.xml
            - -Djboss.host.name=keycloak-0
            - -Djboss.node.name=keycloak-0
            - -Djboss.qualified.host.name=keycloak-0
            - -Djboss.server.name=keycloak-0
            - -Dcluster.instance.service.address="$(KEYCLOAK_0_SERVICE_HOST)"
