apiVersion: v1
kind: Service
metadata:
  name: keycloak-1
spec:
  selector:
    app: keycloak
    petindex: "1"
  ports:
    - port: 7600
    - port: 57600
    - port: 55200
    - port: 45688
    - port: 54200
    - port: 4712
    - port: 4713
