apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
        petindex: "1"
    spec:
      containers:
        - name: keycoak
          image: solsson/keycloak-ha-postgres:2.3.0.Final
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DATABASE
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
            - name: POSTGRES_ROOT_PASSWORD
              value: password
